//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediLinkCB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medication
    {
        public int MedicationID { get; set; }
        public Nullable<int> PrescriptionID { get; set; }
        public string MedicationName { get; set; }
    
        public virtual Prescription Prescription { get; set; }
    }
}
