//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediLinkCB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Patient()
        {
            this.Appointments = new HashSet<Appointment>();
            this.MedicalHistories = new HashSet<MedicalHistory>();
            this.Prescriptions = new HashSet<Prescription>();
        }
    
        public string PatientID { get; set; }
        public string PatientName { get; set; }
        public string PatientSurname { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public Nullable<int> Age { get; set; }
        public string Nationality { get; set; }
        public Nullable<decimal> PatientHeight { get; set; }
        public Nullable<decimal> PatientWeight { get; set; }
        public string Disability { get; set; }
        public string Gender { get; set; }
        public string Race { get; set; }
        public string HomeLang { get; set; }
        public string MaritalStatus { get; set; }
        public string EmailAddress { get; set; }
        public string CellNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appointment> Appointments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedicalHistory> MedicalHistories { get; set; }
        public virtual NextOfKin NextOfKin { get; set; }
        public virtual ResidentialAddress ResidentialAddress { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prescription> Prescriptions { get; set; }
    }
}
